# Numpy

- is short for numerical numpy
- designed for efficient scientific computation
- built on top of c (which works on a lower level than python)
- means it is very fast
- the core of numpy is n-dimentional array object (multidimensional array that holds a group of elements of the same type) 
- it's like a grid that can take any shape and forces all of it's elements to be of the same type 
- making it that way helps numpy to do many vector operations with very high speed

## why use numpy

In [1]:
import time
import numpy as np

In [2]:
# creat an array of 100,000,000 floats between 0 and 1
x = np.random.random(100000000)
x

array([0.46613199, 0.96010145, 0.75994646, ..., 0.82172784, 0.28200051,
       0.94051219])

In [3]:
x.shape

(100000000,)

In [4]:
# the time used for finding the mean of that array using python
start = time.time()
sum(x)/len(x)
print(time.time() - start , "seconds")

22.25968337059021 seconds


In [7]:
# the time for calculating the mean using numpy
start = time.time()
np.mean(x)
print(time.time()-start, "seconds")

0.15560364723205566 seconds


- numpy is extremely faster 
- also useful functions for machine learning problems (ex. holding pixel values for image calssification)
- pandas is built on top of numpy and useful for manipulating datasets

## creating numpy arrays

### 1- use `numpy.array()` function to create them from other array-like objects (ex. regular lists)

In [8]:
#creating ndarray from a list
x = np.array([1, 2, 3, 4, 5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
#useful attributes
x.dtype #returns the datatype of the elements in the arrary

dtype('int32')

- numpy handles more data types than python (check the documentation)

In [10]:
x.shape #returns a tuple of n integers representing the size (of dimension n) 

(5,)

- here it returned only 1 integer (5,) because it's 1D array

In [11]:
# create a 2D array of nested python list 
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
#attributes
print(y.dtype)
print(y.shape)
print(y.size)

int32
(4, 3)
12


### example 3

In [16]:
z = np.array(["hellooo","world","!"])
z

array(['hellooo', 'world', '!'], dtype='<U7')

In [17]:
print(z.dtype) #u5 is unicode strings of 7 characters (mine: the longest number of characters in the array)
print(z.shape)
print(z.size)

<U7
(3,)
3


In [19]:
c = np.array([1,"hello",2.3])
c

array(['1', 'hello', '2.3'], dtype='<U32')

- notice here that the elements are still of the same type (unicode of 32 characters)

In [21]:
c[0] # notice that it upcasted all of the types to the most general type

'1'

In [22]:
w = np.array([1,2.3])
w

array([1. , 2.3])

In [23]:
w.dtype

dtype('float64')

- numpy upcasts the integers to floats to avoid losing precision

In [24]:
#to specify the dtype yourself
x = np.array([1,2.2,5.7], dtype = np.int64)
x

array([1, 2, 5], dtype=int64)

In [25]:
x.dtype

dtype('int64')

## after craeting the array we may save it to be read later or used by another program

In [26]:
np.save("my_array",y)

In [27]:
#to load it into a variable
o = np.load("my_array.npy")
print(o)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 2- using varity of built-in functions 

## array of zeros

In [28]:
# generating numpy arrays
x = np.zeros((3,4)) #takes a tuple of the shape 3x4 and produce array of zeros
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
print(x.dtype,x.shape,x.size)

float64 (3, 4) 12


- by default the dtype is float64 but we can change it

In [30]:
x = np.zeros((3,4), dtype =int)
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## array of ones

In [31]:
x = np.ones((5,6))
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## array of certain constant

In [44]:
x = np.full((3,4),7) 
print(x,x.dtype)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]] int32


In [45]:
x[0,0] = 5

In [46]:
x

array([[5, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

- takes as input the tuple of the shape and the constant to be used
- the dtype of the array is the type of the constant we give it

In [48]:
x = np.full((3,4),'y')
print(x)
print(x.dtype)

[['y' 'y' 'y' 'y']
 ['y' 'y' 'y' 'y']
 ['y' 'y' 'y' 'y']]
<U1


In [55]:
x[0,0] = "you"

In [56]:
x

array([['y', 'y', 'y', 'y'],
       ['y', 'y', 'y', 'y'],
       ['y', 'y', 'y', 'y']], dtype='<U1')

- notice that since the dtype is U1, you was casted to y

In [57]:
x[0,0] = "be you"

In [58]:
x

array([['b', 'y', 'y', 'y'],
       ['y', 'y', 'y', 'y'],
       ['y', 'y', 'y', 'y']], dtype='<U1')

## identity matrix

In [59]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- takes a single integer because it's a square matrix

## diagonal matrix

In [60]:
x = np.diag([1,2,3,4])
x

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## array with specific numerical ranges 

- 1D array of evenly spaced values
 -   arange(start (enclusive) = 0,stop (execlusive) ,step = 1)

In [61]:
x = np.arange(10)
print(x,type(x),x.dtype)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int32


In [62]:
x = np.arange(5,10) #start and stop only
x

array([5, 6, 7, 8, 9])

In [63]:
x = np.arange(5,10,2)
x

array([5, 7, 9])

In [64]:
x = np.arange(5,10,0.5)
x

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

- when we use floating point steps, the output is incinsistent due to finite floating point precision
- so it's better to use linspace for non integer steps

- 2 - linespace(start (inclusive) , stop(inclusive) , n = 50)
 - returns n evenly spaced numbers from start to stop 
 - at least 2 arguments are required

In [65]:
x = np.linspace(0 ,25, 10)
x

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [66]:
x[1] - x[0]

2.7777777777777777

In [67]:
x[2] - x[1]

2.7777777777777777

In [68]:
x[-1] - x[-2]

2.7777777777777786

- that is what we mean by evenly spaced, np.linspace() means linearly spaced

In [69]:
# we can make the end exclusive 
x = np.linspace(0 ,25, 10, endpoint = False)
x

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

## using arange and linspace combined with reshape to make multidimensional arrays 

### reshape combines any numpy array to specified shape 
- but both of them should have the total number of elements to be able to get reshaped correctly

In [70]:
x.shape

(10,)

In [71]:
x = np.reshape(x,(2,5))
x, x.shape

(array([[ 0. ,  2.5,  5. ,  7.5, 10. ],
        [12.5, 15. , 17.5, 20. , 22.5]]),
 (2, 5))

- a great feature about numpy is that some functions can be applied as methods 
- this allows us to apply different functions in sequence in just 1 line

In [72]:
y = np.arange(20).reshape((4,5))
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## arrays of random numbers

- useful in data analysis

## 1 - `random()` to creat array of random numbers between 0 and 1
- 0 is inclusive and 1 is exclusive
- random function contained in the random module in numpy 

In [73]:
x = np.random.random((3,3))
x

array([[0.93943482, 0.82054704, 0.92590428],
       [0.95031107, 0.26014343, 0.91824049],
       [0.54523346, 0.49881694, 0.49165422]])

## 2- randint for random numbers between 2 integers
- randint(lower bound (inclusive), upperbound (exclusive) ,tuple of shape)

In [74]:
x = np.random.randint(4,15,(3,3))
x

array([[ 9, 10, 11],
       [ 5,  8, 14],
       [ 5,  4, 10]])

### 3 - random numbers to satisfy statistical properties

### random numbers of normal distribution given certain mean and standard deviation
- normal(mean, standard deviation, shape)
- if the mean and standard deviation are not given, the default is 0 and 1 (standard normal distribution)
- if the shape is not given, the default is 1

In [77]:
x = np.random.normal(0,0.2,size = (3,3))
x

array([[-0.08885936, -0.06413818,  0.03291731],
       [ 0.13058545, -0.04959204,  0.15201374],
       [ 0.00723745, -0.57587298, -0.0964994 ]])

In [78]:
x.mean()

-0.061356444394779955

In [79]:
x.std()

0.20078347421395

notice they aren't so precise because the size is small, the larger the sampled numbers the more precise the distribution will be 

In [82]:
x = np.random.normal()
x

0.2655500236203892

# manipulate numpy arrays

- numpy arrays are mutable (elements can be changed)
- can also be sliced to retreive any subset of the array (we often slice to separate data)
 - example like when we divide the data into training,validation and testing set

## access and modify the elements by indexing

### access the elements

In [83]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [84]:
print("First element: {}".format(x[0]))
print("Last element: {}".format(x[-1]))

First element: 1
Last element: 5


### modify the accessed elements

In [85]:
x[4] = 20
x

array([ 1,  2,  3,  4, 20])

example 2

In [86]:
x = np.arange(1,10).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

x[row number,column number] both 0 indexed

In [87]:
x[0,0],x[0,1],x[1,0]

(1, 2, 4)

In [88]:
x[0,0] = 20
x

array([[20,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

## delete elements from the array 
 - using delete(array, list of indicies to delete from, axis to delete from-for 2D arrays-) function
 - for 1D it deletes elements, for 2D it deletes entire rows or columns using the axis attribute 
  - axis = 0 means we use the horizontal axis -of rows-
  - axis = 1 means we use the vertical axis -of columns-
- it doesn't delete it in place -instead it returns a copy of that array with the elements deleted-, so we have to assign it back to the variable

In [89]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [90]:
np.delete(x,[0,-1])

array([2, 3, 4])

In [91]:
x

array([1, 2, 3, 4, 5])

In [92]:
x = np.delete(x,[0,-1]) # reassign it to the variable to make it in place
x

array([2, 3, 4])

In [93]:
x = np.arange(1,10).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
np.delete(x,0,axis = 0)

array([[4, 5, 6],
       [7, 8, 9]])

In [95]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
np.delete(x,[0,2],axis = 1)

array([[2],
       [5],
       [8]])

In [97]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## adding elements

## 1.append elements to the array 
 - using the append(array, list of elements to append, axis to append it on -for 2D arrays- )
     - for 1D arrays, values will be appended to the last 
     - for 2D arrays, we append entire row or entire column therefore the sizes must match
 - it also returns a copy of that array with the elements appended

In [98]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [99]:
np.append(x,6)

array([1, 2, 3, 4, 5, 6])

In [100]:
x

array([1, 2, 3, 4, 5])

In [101]:
np.append(x,[6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

### append for 2D arrays 

In [102]:
x = np.arange(1,10).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
np.append(x,[[10,11,12]],axis = 0) #our list is 1x3 and x is 3x3 so the number of columns match 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [104]:
np.append(x, [[4],[7],[10]], axis=1) #our list is 3x1 and x is 3x3 so the rows match 

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [105]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- notice that in all the previous example x didn't change so, in order to change it assign it back

In [106]:
x = np.append(x, [[4],[7],[10]], axis=1)
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

## insert into numpy array
- it is different than append as in here we specify where to add it (in append it is always to the last of the array)
 - for 1D inserting values 
 - for 2D inserting a whole row or column using axis attribute
 - using `insert(array, index, elements, axis -for 2D- )` **axis** is the new parameter here to append as in here we can specify where to insert the elements
  - inserts the elements to the array right before the index, along the specific axis

In [107]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [108]:
x = np.insert(x, 2, [99,100])
x

array([  1,   2,  99, 100,   3,   4,   5])

In [109]:
x = np.arange(1,10).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
np.insert(x,-1,[99,99,99],axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99],
       [ 7,  8,  9]])

In [111]:
np.insert(x,-1,[99,99,99],axis = 1)

array([[ 1,  2, 99,  3],
       [ 4,  5, 99,  6],
       [ 7,  8, 99,  9]])

In [112]:
np.insert(x,3,[99,99,99],axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [99, 99, 99]])

## stack numpy arrays

### on top of each other 
- using `np.vstack(tuple of arrays to be stacked)` for vertical stacking 
- the shape of the arrays must match (to stack arrays below each other, they must have the same number of columns)

In [113]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [114]:
y = np.array([[4,5,6],[7,8,9]])
y

array([[4, 5, 6],
       [7, 8, 9]])

In [115]:
z = np.vstack((x,y))
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## beside each other 

In [118]:
y = np.array([[99],[99],[99]])
y, y.shape

(array([[99],
        [99],
        [99]]),
 (3, 1))

In [120]:
z = np.hstack((z,y))
z

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

- to stack arrays beside each other, they must have the same number of rows
- in here 3x3 and 3x1 have the same number of rows -3- so we can stack them beside each other, and the result will be 3x(1+3) -> 3x4

# slicing numpy arrays

- in addition to accessing individual elements using indexing 
- we can also access a subset of the array with slicing
- we have 3 ways of slicing
 - ndarray[start index : end index] end exluded 
 - ndarray[start index :] we didn't specify end index so it takes till the end (included)
 - ndarray[: end index] end excluded
- if we slice a multidimensional array, we have to specify the slice for each dimension 
 - for 2D array[start:end (indices to grab from the row) , start:end (indicies to grab from the columns)]
- slicing creates a window of the same object even if we assign the slice to another variable 

In [121]:
x = np.arange(1,21).reshape((4,5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

here it's 2D so if we will slice we specify it in the 2 dimensions

In [122]:
z = x[1:4 , 2:5] 
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [123]:
z = x[1: , 2:]
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [124]:
#slice the first 3 rows and first 2 columns
z = x[:3 , :2] #take row 0,1,2 and columns 0,1
z

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

- common practice

In [125]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [126]:
indicies = np.array([0,1,2])
z = x[indicies,1]
z, z.shape

(array([ 2,  7, 12]), (3,))

In [127]:
z = x[2,indicies]
z

array([11, 12, 13])

In [128]:
#slice all the elements in the last column
z = x[: , 4] #or -1 instead of 4
z

array([ 5, 10, 15, 20])

- notice that we got it as a rank1 array 
- if we want it as a rank 2 array

In [129]:
z = x[: , 4:5]
z

array([[ 5],
       [10],
       [15],
       [20]])

# important!
- when we slice an array and save it to a new variable, the slice isn't deeply copied
- changing in the slice also changes the original array 
- slicing only creates a view of the original data to work with

In [131]:
x,z

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]),
 array([[ 5],
        [10],
        [15],
        [20]]))

In [132]:
z[3,0] = 99
z

array([[ 5],
       [10],
       [15],
       [99]])

In [133]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 99]])

## to deep copy it use `np.copy()` or `array.copy()`
- it can be used as a function of as a method like reshape()

In [134]:
x = np.arange(1,21).reshape((4,5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### as a function

In [135]:
z = np.copy(x[1: , 2:])
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [136]:
z[-1,-1] = 100
z

array([[  8,   9,  10],
       [ 13,  14,  15],
       [ 18,  19, 100]])

In [137]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### as a method

In [138]:
w = x[1:, 2:].copy()
w

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

## functions to slice specific elements

## diag() for diagonal elements
- retrieves the diagonal elements of the array
- np.diag(array, k = 0) k is the offset of the diagonal
- if k > 0, it is above the main diagonal
- if k < 0, it is below the main diagonal

In [141]:
x = np.arange(1,21).reshape((4,5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [142]:
diagonal_elements = np.diag(x)
diagonal_elements

array([ 1,  7, 13, 19])

### using offset to grab diagonals with respect to the main diagonal

In [143]:
above_diagonal = np.diag(x,k=1)
above_diagonal

array([ 2,  8, 14, 20])

In [145]:
under_diagonal = np.diag(x,k=-1) # -1 means below the main diagonal by one not the last index 
under_diagonal

array([ 6, 12, 18])

## unique() for unique elements in an array

In [146]:
x = [[1,1,1],[2,2,2],[3,3,3]]
x

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [147]:
x = np.array(x)
x

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [148]:
np.unique(x)

array([1, 2, 3])

# boolean indexing 

- so far we have selected elements using indicies 
- this is useful when we know the exact indicies to be selected 
- but sometimes,we don't know the indicies of the elements we want, we only know a logical condition to select the elements based upon 
 - ex. 10,000x10,000 array and we want to selected all integers less than 20
- in this case, we use boolean indexing to select elements based on logical arguments rather than explicit indicies
- the syntax is `array[logical condition]`

In [149]:
x = np.arange(25).reshape((5,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [150]:
# To select all elements > 10
x[x > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [151]:
x[(x > 10) & (x <= 20)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

we can even use it to assign the elements

In [152]:
x[(x > 10) & (x <= 20)] = 0
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0, 21, 22, 23, 24]])

# set operations on numpy arrays
- allow us to do set operations on the arrays
- useful when comparing 2 numpy arrays

In [153]:
x = np.array([1,2,3,4,5])
y = np.array([4,5,6,7,8])

In [154]:
# to find the intersections between the sets (arrays)
np.intersect1d(x,y)

array([4, 5])

In [155]:
np.setdiff1d(x,y) # differencce (what is in x and not in y)

array([1, 2, 3])

In [156]:
np.setdiff1d(y,x) # difference (what is in y and not in x)

array([6, 7, 8])

In [157]:
np.union1d(x,y) #find the union 

array([1, 2, 3, 4, 5, 6, 7, 8])

## Set operations for 2D arrays

In [165]:
u = np.array( [[3,3,3],[4,5,6]])
o = np.array([[4,5,6],[7,8,9]])
u,o

(array([[3, 3, 3],
        [4, 5, 6]]),
 array([[4, 5, 6],
        [7, 8, 9]]))

In [166]:
np.intersect1d(u,o)

array([4, 5, 6])

In [167]:
np.union1d(o,u)

array([3, 4, 5, 6, 7, 8, 9])

# sorting numpy arrays
- we can use the `np.sort()` function, can also be applied as a method
 - when we use the sort as a **function**, it is sorted **out of place**
 - when we use sort as a **method**,it is sorted **in place** (the original array is changed)

## as a function

In [168]:
x = np.array([2,1,4,3,5])
x

array([2, 1, 4, 3, 5])

In [169]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [170]:
x

array([2, 1, 4, 3, 5])

In [171]:
x = np.sort(x)
x

array([1, 2, 3, 4, 5])

## as a method

In [172]:
x = np.array([2,1,4,3,5])
x

array([2, 1, 4, 3, 5])

In [173]:
x.sort()
x

array([1, 2, 3, 4, 5])

## sorting 2D array 
- either by rows or by columns 
    - for rows `axis = 0`, we will loop over the columns and sort all the rows 
- we use the axis attribute 

In [175]:
x = np.random.randint(1,10,(5,5))
x

array([[7, 4, 4, 9, 9],
       [7, 1, 2, 3, 1],
       [6, 4, 1, 5, 6],
       [3, 1, 8, 4, 2],
       [8, 3, 2, 9, 3]])

## sort by rows

In [176]:
np.sort(x,axis = 0)

array([[3, 1, 1, 3, 1],
       [6, 1, 2, 4, 2],
       [7, 3, 2, 5, 3],
       [7, 4, 4, 9, 6],
       [8, 4, 8, 9, 9]])

## sort by columns
- we will loop over the rows, and for each row, we will sort the columns

In [177]:
np.sort(x,axis = 1)

array([[4, 4, 7, 9, 9],
       [1, 1, 2, 3, 7],
       [1, 4, 5, 6, 6],
       [1, 2, 3, 4, 8],
       [2, 3, 3, 8, 9]])

# arithmetic operations on arrays
- numpy allows element wise operations and matrix operations

## element wise operations

In [178]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

### using symbols

In [179]:
x + y

array([ 6,  8, 10, 12])

In [180]:
x - y

array([-4, -4, -4, -4])

In [181]:
x * y

array([ 5, 12, 21, 32])

In [182]:
x / y

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

for 2D arrays

In [183]:
x = np.array([1,2,3,4]).reshape((2,2))
x

array([[1, 2],
       [3, 4]])

In [184]:
y = np.array([5,6,7,8]).reshape(2,2)
y

array([[5, 6],
       [7, 8]])

In [185]:
x+y

array([[ 6,  8],
       [10, 12]])

In [186]:
x-y

array([[-4, -4],
       [-4, -4]])

In [187]:
x*y

array([[ 5, 12],
       [21, 32]])

In [188]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

### using functions
- both of them do the same operations
- but here, the functions have options that we can tweak using attributes and methods

In [193]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [194]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [195]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [196]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

for 2D

In [197]:
x = np.array([1,2,3,4]).reshape((2,2))
x

array([[1, 2],
       [3, 4]])

In [198]:
y = np.array([5,6,7,8]).reshape(2,2)
y

array([[5, 6],
       [7, 8]])

In [199]:
np.add(x,y) #and so on

array([[ 6,  8],
       [10, 12]])

## apply mathematical functions 

### square root

In [200]:
x

array([[1, 2],
       [3, 4]])

In [201]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

### exponential 

In [202]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

### power

In [203]:
np.power(x,2)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

## apply statistical functions

### average

In [204]:
np.mean(x)

2.5

In [205]:
x.mean()

2.5

### average of rows or columns

In [206]:
x

array([[1, 2],
       [3, 4]])

In [207]:
print("the average of each column -we average the rows for each column-: {}".format(x.mean(axis = 0))) #note axis = 0!!!

the average of each column -we average the rows for each column-: [2. 3.]


In [208]:
print("average of each row: {}".format(x.mean(axis = 1))) # we work on the columns for each row

average of each row: [1.5 3.5]


### sum 

In [209]:
x.sum()
x.sum(axis = 0), x.sum(axis = 1)

(array([4, 6]), array([3, 7]))

### standard deviation of an array 

In [210]:
x.std()

1.118033988749895

In [211]:
np.median(x)

2.5

In [212]:
x.max()

4

In [213]:
x.min()

1

## braodcasting 
- numpy sometimes use it to complete the operations
- numpy use it to handle element wise operations for arrays of different shapes
- so in order to do element wise operations, the arrays must have the same shape or be broadcastable

### braodcast a constant 

In [214]:
x = np.array([1,2,3,4]).reshape((2,2))
x

array([[1, 2],
       [3, 4]])

In [215]:
y = np.array([5,6,7,8]).reshape(2,2)
y

array([[5, 6],
       [7, 8]])

In [216]:
x+3 # 3 is braodcasted to be the same shape as x

array([[4, 5],
       [6, 7]])

In [217]:
x-3

array([[-2, -1],
       [ 0,  1]])

In [218]:
x*3

array([[ 3,  6],
       [ 9, 12]])

In [219]:
x/3

array([[0.33333333, 0.66666667],
       [1.        , 1.33333333]])

## broadcast a matrix for another
- either we match the rows and it is broadcasted along the columns
- or match the columns and it is broadcasted among the rows
- in general if we can expand the smaller array to fit the larger's shape

In [220]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [221]:
y = np.arange(3)
y

array([0, 1, 2])

In [222]:
x.shape,y.shape

((3, 3), (3,))

In [223]:
x+y # y is broadcasted to be [[0,1,2],[0,1,2],[0,1,2]]

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [224]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [225]:
z = np.arange(3).reshape(3,1)
z

array([[0],
       [1],
       [2]])

In [226]:
x+z

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])